site_name: Azure Project

repo_url: https://github.com/Vasanthabalaji01/Azure

theme:
  name: material
  palette:
    - scheme: default
      primary: light-blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: light-blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: img/Mr.Cloudexplorer_logo.png
  favicon: img/Mr.Cloudexplorer_logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - header.autohide
    - navigation.tabs

nav:
  - Home: index.md
  - About: about.md
  - Core Services:
      - Intro: Azure_service/intro.md
      - Compute:
          - Virtual Machines: 'Azure_service/compute/vm/vm.md'
          - Azure Batch: 'Azure_service/compute/azure_batch/azure_batch.md'
          - Container Instances: 'Azure_service/compute/container_instances/container_instances.md'
          - Container Apps: 'Azure_service/compute/container_app/container_app.md'
          - Kubernetes Service: 'Azure_service/compute/kubernetes_service/kubernetes_service.md'
          - Virtual Desktop: 'Azure_service/compute/virtual_desktop/virtual_desktop.md'
          - VM Scale Sets: 'Azure_service/compute/vm_scale/vm_scale.md'
          - Azure Arc: 'Azure_service/compute/azure_arc/azure_arc.md'
      - Storage:
          - Azure NetApp Files: 'Azure_service/storage/azure_netapp_files/azure_netapp_files.md'
          - Azure Files: 'Azure_service/storage/azure_files/azure_files.md'
          - Managed Disks: 'Azure_service/storage/managed_disks/managed_disks.md'
          - Data Lake Storage: 'Azure_service/storage/data_lake_storage/data_lake_storage.md'
          - Databases: 'Azure_service/storage/databases/databases.md'
          - MySQL Database: 'Azure_service/storage/mysql_database/mysql_database.md'
          - MariaDB Database: 'Azure_service/storage/mariadb_database/mariadb_database.md'
          - PostgreSQL Database: 'Azure_service/storage/postgresql_database/postgresql_database.md'
          - SQL Database: 'Azure_service/storage/sql_database/sql_database.md'
          - Cosmos DB: 'Azure_service/storage/cosmos_db/cosmos_db.md'
      - Networking:
          - Application Gateway: 'Azure_service/networking/application_gateway/application_gateway.md'
          - CDN: 'Azure_service/networking/cdn/cdn.md'
          - DNS: 'Azure_service/networking/dns/dns.md'
          - Firewall: 'Azure_service/networking/firewall/firewall.md'
          - Load Balancer: 'Azure_service/networking/load_balancer/load_balancer.md'
          - Virtual Network: 'Azure_service/networking/virtual_network/virtual_network.md'
          - VPN Gateway: 'Azure_service/networking/vpn_gateway/vpn_gateway.md'
      - Management & Governance:
          - Automation: 'Azure_service/management_and_governance/automation/automation.md'
          - Advisor: 'Azure_service/management_and_governance/advisor/advisor.md'
          - Monitor: 'Azure_service/management_and_governance/monitor/monitor.md'
          - Policy: 'Azure_service/management_and_governance/policy/policy.md'
          - Cost Management: 'Azure_service/management_and_governance/cost_management/cost_management.md'
          - Defender for Cloud: 'Azure_service/management_and_governance/defender_for_cloud/defender_for_cloud.md'
      - AI & Machine Learning:
          - AI Services: 'Azure_service/ai_and_machine_learning/ai_services/ai_services.md'
          - Azure Databricks: 'Azure_service/ai_and_machine_learning/azure_databricks/azure_databricks.md'
          - Machine Learning: 'Azure_service/ai_and_machine_learning/machine_learning/machine_learning.md'
      - Analytics:
          - Data Explorer: 'Azure_service/analytics/data_explorer/data_explorer.md'
          - Data Factory: 'Azure_service/analytics/data_factory/data_factory.md'
          - Databricks: 'Azure_service/analytics/databricks/databricks.md'
          - HDInsight: 'Azure_service/analytics/hdinsight/hdinsight.md'
          - Synapse Analytics: 'Azure_service/analytics/synapse_analytics/synapse_analytics.md'
          - Time Series Insights: 'Azure_service/analytics/time_series_insights/time_series_insights.md'
      - Development & DevOps:
          - API Management: 'Azure_service/development_and_devops/api_management/api_management.md'
          - App Configuration: 'Azure_service/development_and_devops/app_configuration/app_configuration.md'
          - App Service: 'Azure_service/development_and_devops/app_service/app_service.md'
          - Azure DevOps: 'Azure_service/development_and_devops/azure_devops/azure_devops.md'
          - Functions: 'Azure_service/development_and_devops/functions/functions.md'
  - Architecture:
      - Intro: Cloud_Architecture/intro.md
      - One-Tier: Cloud_Architecture/One_Tier/one_tier.md
      - Two-Tier: Cloud_Architecture/Two_Tier/two_tier.md
      - Three-Tier: Cloud_Architecture/Three_Tier/three_tier.md
      - N-Tier: Cloud_Architecture/N_Tier/n_tier.md
      - Serverless: Cloud_Architecture/Serverless/serverless.md
      - Microservices: Cloud_Architecture/Microservices/microservices.md
      - Event-Driven: Cloud_Architecture/Event_Driven/event_driven.md
      - Hybrid: Cloud_Architecture/Hybrid/hybrid.md
  - Security:
      - Intro: Cloud_Security/intro.md

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Vasanthabalaji01
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/vasanthabalaji
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/mrcloudexplorer
